#!/bin/sh

set -e
. /usr/share/debconf/confmodule

for i in $(list-devices disk); do
    if block-attr --type "$i" | grep -q "iso9660"; then
        continue
    fi
    echo "Selected $i"
    db_set partman-auto/disk "$i"
    db_set grub-installer/bootdev "$i"
    db_fset grub-installer/bootdev seen "true"
    break
done
